### ISSUE TITLE
`stretch_urdf_ros_update.py` hardcoded for hello-robot user

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_urdf#13]
https://github.com/hello-robot/stretch_urdf/blob/9c9fbeb919cbb3f9df682fe4b6b6a79f9c47410f/tools/stretch_urdf_ros_update.py#L62

If the robot has other users, this tool won't work in those other users.

**Comment by Artificys** [comment]
Another thing with this, is that when trying to create a new workspace using _stretch_create_ament_workspace.sh_, it'll copy the urdf directory to the ament_ws instead of whatever new workspace you're trying to create. Which then crashes the script when 
```
ros2 run stretch_calibration update_uncalibrated_urdf
```
Can't find the xacro files inside the new workspace.

**Comment by hello-binit** [comment]
Thanks @Artificys, good point. And thanks for moving https://github.com/hello-robot/stretch_install/issues/64 here.

I believe @hello-fazil is working on fixing this.

**Comment by hello-fazil** [comment]
This issue if fixed with the commit https://github.com/hello-robot/stretch_urdf/commit/345cd7b186396d3637403774a3b989dbc1ab29b2
